### ISSUE TITLE
can't reproduce your results

### ISSUE THREAD

**Issue by Paseam** [ZZUTK/Face-Aging-CAAE#3]
I have downloaded your codes, and run it successfully, but my results is inferior to yours in losssing identity, can you help me?
![image](https://cloud.githubusercontent.com/assets/8642716/24574028/510db9e2-16bf-11e7-97ca-824a116ba280.png)

**Comment by ZZUTK** [comment]
You may first remove the effect of the discriminators to see what happen because the discriminators may cause your problem. Please refer to the line 203 of FaceAging.py, setting all parameters to zero (modify all 0.0001 to 0). Then, it will be equivalent to autoencoder, which is supposed to generate blurred faces, but it is more stable. Then, you may slightly increase the weight of G_img_loss to expect more texture on generated faces. Hope this help.

**Comment by Paseam** [comment]
thanks! it helped me

**Comment by shz1314** [comment]
hi @Paseam 
i have the same problem.first i train the eg_loss first,then i change the gan loss from 0 to 0.0001 ,but i get the image which is not good.if you tell me your weight of loss ,i will be very appreciate
